### ISSUE TITLE
后台页面和功能做得很棒，但是有个小问题想请您赐教。后台的所有添加按钮，html里面用{toolbar id="toolbar"}{/toolbar}来展示按钮控件，但是点击按钮会报错，我看了代码不太懂，具体的你可以看我发的图片，谢谢。

### ISSUE THREAD

**Issue by CXINT** [Astonep/tp-admin#11]
![2017-08-10_175750](https://user-images.githubusercontent.com/26117209/29165455-4e784484-7df5-11e7-860b-81adcc0b68b1.png)
![2017-08-10_175940](https://user-images.githubusercontent.com/26117209/29165456-4fc72b84-7df5-11e7-8d1d-a75c1e765e11.png)

**Comment by Aierui** [comment]
TP的标签功能

**Comment by zeelo** [comment]
我的数据库好像表不全。点添加都报网络连接失败，只有权限页面能点添加弹出表单。
