### ISSUE TITLE
gridView.js中$this.uniqueId建议不要写死

### ISSUE THREAD

**Issue by BoundlessHaung** [Astonep/tp-admin#2]
gridView.js中$this.uniqueId建议不要写死
建议增加可以修改$this.uniqueId的方法或是在需要使用的方法中增加传参，或者其他方式 : )

**Comment by BoundlessHaung** [comment]
建议
gridView.js    第17行 改为：this.uniqueId = this.$table.data('uniqueId');
gridView.js    第40行 改为：uniqueId: $this.$table.data('uniqueId'),

**Comment by Aierui** [comment]
谢谢你的建议
