### ISSUE TITLE
数据获取失败

### ISSUE THREAD

**Issue by zjn000** [Astonep/tp-admin#3]
![image](https://cloud.githubusercontent.com/assets/16486112/22873357/941014d6-f1fa-11e6-95ff-ff9c8ddc9214.png)
输出$request的值：
![image](https://cloud.githubusercontent.com/assets/16486112/22873415/f39e903a-f1fa-11e6-830e-61eb007c45cb.png)
数据库有正常导入，但数据库查询参数在user表中明显没有其字段，请问代码是否有遗漏还是欠缺配置什么

**Comment by BoundlessHaung** [comment]
参数怎么会多出来一个 /admin/user/fetlist

**Comment by zjn000** [comment]
![image](https://cloud.githubusercontent.com/assets/16486112/22910428/e89675f0-f294-11e6-86ca-eca8a5d960cb.png)
将传入参数进行打印，里面就出现了这个
![image](https://cloud.githubusercontent.com/assets/16486112/22910459/252cc28a-f295-11e6-966e-1c431ce49aba.png)
所以才纳闷为什么在查询参数里会出现这么个值，又不像是要用来权限判断

**Comment by BoundlessHaung** [comment]
我试了一下我这里无法重现出这个问题，如果修改了什么的话，可以追溯下，要是实在不行的话可以暂时手动unset掉/admin/user/fetlist

**Comment by zjn000** [comment]
额，我里面只修改了/public/.htaccess中index.php后面加上一个问号，其他没改动， 会不会是环境的问题，我用的是phpstudy，版本为PHP5.5

**Comment by BoundlessHaung** [comment]
`if (isset($request['/admin/user/fetlist'])) {
    unset($request['/admin/user/fetlist']);
}`

如果找不到原因的话可以在$request = request()->param();加上上面的代码来临时解决

**Comment by zjn000** [comment]
是的，这样可以临时解决，但问题是所有的都会出现多出那url参数，也就是说，每个列表我都需要去unset掉

**Comment by BoundlessHaung** [comment]
headers看下？

**Comment by zjn000** [comment]
![image](https://cloud.githubusercontent.com/assets/16486112/22912759/044978d0-f2a2-11e6-8185-47dce5c47359.png)
这里么？
还是说这里
![image](https://cloud.githubusercontent.com/assets/16486112/22912828/751bcfe0-f2a2-11e6-85b0-2d1ac50e2327.png)

**Comment by BoundlessHaung** [comment]
请求的headers

**Comment by zjn000** [comment]
![image](https://cloud.githubusercontent.com/assets/16486112/22912964/290b47ba-f2a3-11e6-822a-4dcbd8ae79aa.png)

**Comment by BoundlessHaung** [comment]
还有一种方式，那就是获取参数的那里改成$request = input("");呢？

**Comment by zjn000** [comment]
是的，但获取到的值还是一样的，目前情况就是不清楚为何多出那URL查询参数

**Comment by BoundlessHaung** [comment]
一脸懵逼，换个环境试试？比如XAMPP？

**Comment by zjn000** [comment]
好的，我自己尝试看看能不能解决

**Comment by zjn000** [comment]
已找出问题,这是项目环境问题，如果用phpstudy需要将/public/.htaccess中的内容替换成以下代码

<IfModule mod_rewrite.c> 
Options +FollowSymlinks -Multiviews
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteRule ^(.*)$ index.php [L,E=PATH_INFO:$1] 
</IfModule>

**Comment by Aierui** [comment]
前段时间忙，没有及时为大家解决问题。抱歉。
