### ISSUE TITLE
发现一个bug？

### ISSUE THREAD

**Issue by zjn000** [Astonep/tp-admin#5]
例如：当权限管理列表的数据超过5条时，没有自动分页，另求教：此项目中，如何在界面自定义查询字段，才能在controller中能获取到，即
![image](https://cloud.githubusercontent.com/assets/16486112/23493734/efe3f240-ff48-11e6-959a-8a00add36057.png)图中的map参数如何获取？

**Comment by Aierui** [comment]
分页分为两种：

- 前端分页

- 后端分页
