### ISSUE TITLE
用户管理页面，增加和删除点击后，路径不对

### ISSUE THREAD

**Issue by qinpengwei** [Astonep/tp-admin#7]
在我的环境上部署好后，我们把访问地址重新配置了，改成http://www.domain/项目文件夹/public/index.php/admin/user/index,这种访问结构，结果用户管理页面的添加和删除按钮功能不能用了，报错的路径是http://www.domain/admin/user/index。求教

**Comment by elingembkq222** [comment]
后台伪静态 去掉index.php 或者手动修改文件 添加index.php
